const clearanceList = {
  quartz: [
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price1: 0,
      price2: 0,
      contact: "",
    },
  ],
  porcelain: [
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price1: 0,
      price2: 0,
      contact: "",
    },
  ],
  onyx: [
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price1: 0,
      price2: 0,
      contact: "",
    },
  ],
  marble: [
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price1: 0,
      price2: 0,
      contact: "",
    },
  ],
};
