import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Promo from "@/components/Promo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-100`}>
        <Promo />
        <div className="2xl:px-28">
          <header className="">
            <Image
              priority
              src="/stonica.png"
              alt=""
              width={250}
              height={150}
              className="w-60 mt-5"
            />
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
