export const clearanceList = {
  quartz: [
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
  ],
  porcelain: [
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400],
      contact: "",
    },
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400],
      contact: "",
    },
  ],
  onyx: [
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
  ],
  marble: [
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
    {
      img: "",
      alt: "",
      name: "",
      dimension: "",
      thickness: "",
      country: "",
      quantity: 0,
      price: [500, 400, 200],
      contact: "",
    },
  ],
};
